"""
Sequence constraint decorators.
"""

from dataclasses import dataclass
from typing import Any, Callable, TypeVar

from oigen.decorators.base import Constraint, ConstraintRegistry, add_constraint
from oigen.errors import ConstraintError
from oigen.generators import BaseGenerator

F = TypeVar("F", bound=Callable[..., BaseGenerator])


# ============================================================================
# Sequence Constraints
# ============================================================================


@dataclass
class RelationConstraint(Constraint):
    """Constraint for relationships between adjacent elements."""

    predicate: Callable[[Any, Any], bool]

    def validate(self, generator: BaseGenerator, registry: ConstraintRegistry) -> None:
        if not callable(self.predicate):
            raise ConstraintError(
                "with_relation: predicate must be callable",
                suggestion="Use a function like lambda a, b: a < b",
            )

    def apply(self, generator: BaseGenerator, context: dict[str, Any]) -> None:
        context["relation_predicate"] = self.predicate

    @property
    def priority(self) -> int:
        return 20


@dataclass
class MonotonicConstraint(Constraint):
    """Constraint for monotonic sequences."""

    direction: str  # "increasing", "decreasing", "non_increasing", "non_decreasing"
    strict: bool

    def validate(self, generator: BaseGenerator, registry: ConstraintRegistry) -> None:
        valid_directions = ("increasing", "decreasing", "non_increasing", "non_decreasing")
        if self.direction not in valid_directions:
            raise ConstraintError(
                f"monotonic: direction must be one of {valid_directions}, "
                f"got '{self.direction}'",
                suggestion="Use 'increasing', 'decreasing', 'non_increasing', or 'non_decreasing'",
            )

    def apply(self, generator: BaseGenerator, context: dict[str, Any]) -> None:
        context["monotonic"] = self.direction
        context["monotonic_strict"] = self.strict

    @property
    def priority(self) -> int:
        return 15  # Apply before general relation


@dataclass
class PrefixSumBoundedConstraint(Constraint):
    """Constraint for bounded prefix sums."""

    max_val: int | float

    def validate(self, generator: BaseGenerator, registry: ConstraintRegistry) -> None:
        # Get element generator to check compatibility
        element = getattr(generator, "element", None)
        if element is not None:
            min_val = getattr(element, "min_val", None)
            if min_val is not None and min_val < 0:
                raise ConstraintError(
                    "prefix_sum_bounded: may not work well with negative elements",
                    suggestion="Consider using non-negative element generators",
                )

    def apply(self, generator: BaseGenerator, context: dict[str, Any]) -> None:
        context["prefix_sum_max"] = self.max_val

    @property
    def priority(self) -> int:
        return 20


# ============================================================================
# Decorator Functions
# ============================================================================


def with_relation(predicate: Callable[[Any, Any], bool]) -> Callable[[F], F]:
    """Add a relationship constraint between adjacent elements.

    The predicate receives consecutive elements (a, b) and should return True
    if the relationship is satisfied. Generation will retry until the constraint
    is satisfied or max retries is exceeded.

    Args:
        predicate: Function (a, b) -> bool for adjacent elements.

    Example:
        @with_relation(lambda a, b: abs(a - b) <= 5)  # Adjacent differ by at most 5
        def smooth_sequence():
            return Sequence(Int(1, 100), length=10)
    """
    return add_constraint(RelationConstraint(predicate))


def monotonic(
    direction: str = "increasing",
    strict: bool = True,
) -> Callable[[F], F]:
    """Constrain the sequence to be monotonic.

    For efficiency, this uses direct construction rather than retry.
    The sequence is generated by sorting or using cumulative construction.

    Args:
        direction: One of "increasing", "decreasing", "non_increasing", "non_decreasing".
        strict: If True, require strict monotonicity (no equal adjacent elements).

    Example:
        @monotonic("increasing")  # Strictly increasing
        def sorted_sequence():
            return Sequence(Int(1, 100), length=10)

        @monotonic("non_decreasing", strict=False)  # Allow equal elements
        def non_decreasing_sequence():
            return Sequence(Int(1, 100), length=10)
    """
    return add_constraint(MonotonicConstraint(direction, strict))


def prefix_sum_bounded(max_val: int | float) -> Callable[[F], F]:
    """Constrain all prefix sums to not exceed max_val.

    For a sequence [a, b, c, ...], ensures:
    - a <= max_val
    - a + b <= max_val
    - a + b + c <= max_val
    - ...

    Args:
        max_val: Maximum value for any prefix sum.

    Example:
        @prefix_sum_bounded(1000)
        def bounded_prefix_sequence():
            return Sequence(Int(1, 100), length=20)
    """
    return add_constraint(PrefixSumBoundedConstraint(max_val))
